spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

server:
  port: 8081

jwt:
  secret: skyBookerSecretKeyForJWTTokenValidationPurpose123456789
  expiration: 86400000

google:
  oauth:
    client-id: YOUR_GOOGLE_CLIENT_ID_HERE

logging:
  level:
    ROOT: INFO
    com.skyBooker: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /auth/v3/api-docs
  swagger-ui:
    path: /auth/swagger-ui.html